include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Type safety
    avoid_dynamic_calls: true

    # Code style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_super_parameters: true

    # Documentation
    public_member_api_docs: true

    # Error prevention
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    unnecessary_lambdas: true
